casomira/casomira/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]

casomira/main/urls.py
from django.urls import path

from . import views
from .views import flights

app_name = "main"

urlpatterns = [
    path("", views.index, name="main"),
    path("entry", views.entry, name="entry"),
    path("flights", views.flights, name="flights"),
    path("finished_flights", views.finished_flights, name="finished_flights"),
    path("flights/<int:id>/edit", views.finished_flights_update, name="edit"),
    path("end_day", views.end_day, name="end_day"),
]

casomira/main/models.py
from django.db import models
import math
from django.db.models import DurationField


# Create your models here


class Person(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200, null=True)
    nickname = models.CharField(max_length=200, null=True)
    active = models.BooleanField(default=False)
    in_the_sky = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.nickname} {self.last_name}"


class Aircraft(models.Model):
    aircraft_type = models.CharField(max_length=60)
    registration = models.CharField(max_length=15)
    active = models.BooleanField(default=False)
    in_the_sky = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.aircraft_type}, {self.registration}"


class Flight(models.Model):
    date = models.DateField("date of provoz", auto_now_add=True)
    takeoff = models.DateTimeField("takeoff", default=None, null=True, blank=True)
    landing = models.DateTimeField("landing", default=None, null=True, blank=True)
    student = models.ForeignKey(
        Person,
        on_delete=models.RESTRICT,
        related_name="student",
        null=True,
        default=None,
        blank=True,
    )
    captain = models.ForeignKey(
        Person, on_delete=models.RESTRICT, related_name="captain", null=True
    )
    aircraft = models.ForeignKey(
        Aircraft, on_delete=models.RESTRICT, related_name="letadlo", null=True
    )
    # duration = models.DurationField('duration', )

    def __str__(self):
        return f"{self.date}, {self.takeoff}, {self.landing}, {self.student}, {self.captain}, {self.aircraft}"

    @property
    def duration(self):
        landing = self.landing
        takeoff = self.takeoff
        time_delta = math.ceil((landing - takeoff).total_seconds() / 60)
        return time_delta

    # duration = property(__duration)


casomira/main/forms.py
from django import forms
from .models import Flight


class FlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        fields = ["student", "captain", "aircraft", "takeoff", "landing"]

casomira/main/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from main.models import Person, Aircraft, Flight
from django.shortcuts import redirect
from datetime import datetime, timezone, timedelta
from datetime import date
from .forms import FlightForm
import csv

def index(request):
    return render(request, "main/index.html")


def entry(request):
    #check if there is no valid entry yet
    #request only the needed values .values('active', 'name', 'id')
    people_active = Person.objects.values_list("active").filter(active = True)
    aircrafts_active = Aircraft.objects.values_list("active").filter(active = True)

    if people_active or aircrafts_active:
        return HttpResponseRedirect("flights")

    person_list = Person.objects.values("id", "first_name", "last_name").order_by("id")
    aircraft_list = Aircraft.objects.values("id", "registration").order_by("id")

    context = {
        "person_list": person_list,
        "aircraft_list": aircraft_list,
    }

    if request.method == "POST":
        person_choosen = request.POST.getlist("person_choosen")
        aircraft_choosen = request.POST.getlist("aircraft_choosen")

    #Person.object.filter(id__in=person_list).update(active=True)
        Person.objects.filter(id__in=person_choosen).update(active=True)
        Aircraft.objects.filter(id__in=aircraft_choosen).update(active=True)

        return redirect("main:flights")

    return render(request, "main/entry.html", context)


def flights(request):

    #Check if there is an active running entry, if not, redirect to the start entry page
    people_active_count = Person.objects.values_list("active").filter(active = True).count()
    aircrafts_active_count = Aircraft.objects.values_list("active").filter(active = True).count()
    if people_active_count == 0 or aircrafts_active_count == 0:
        return HttpResponseRedirect("entry")


    flights_list_landed = Flight.objects.filter(landing__isnull = False).order_by("takeoff")
    flights_list_not_landed = Flight.objects.filter(landing__isnull = True).order_by("takeoff")

    person_active_list = Person.objects.order_by("id").filter(active=True, in_the_sky=False)
    aircraft_active_list = Aircraft.objects.order_by("id").filter(active=True, in_the_sky=False)


    context = {
        "flights_list": flights_list_landed,
        "person_active_list": person_active_list,
        "aircraft_active_list": aircraft_active_list,
        "flights_not_landed":  flights_list_not_landed,
    }

    if request.method == "POST" and "confirm_takeoff" in request.POST:

        Flight(
            aircraft_id=request.POST.get("aircraft"),
            captain_id=request.POST.get("capitan"),
            student_id=request.POST.get("student"),
            takeoff=datetime.now(timezone.utc),
        ).save()
        Person.objects.filter(id=request.POST.get("capitan")).update(in_the_sky=True)
        Person.objects.filter(id=request.POST.get("student")).update(in_the_sky=True)
        Aircraft.objects.filter(id=request.POST.get("aircraft")).update(in_the_sky=True)

        if request.POST.get("aircraft_bow") == None:
            pass
        else:
            Flight(
                aircraft_id=request.POST.get("aircraft_bow"),
                captain_id= request.POST.get("capitan_bow"),
                takeoff=datetime.now(timezone.utc)
            ).save()
            Person.objects.filter(id=request.POST.get("capitan")).update(in_the_sky=True)
            Person.objects.filter(id=request.POST.get("student")).update(in_the_sky=True)
            Aircraft.objects.filter(id=request.POST.get("aircraft")).update(in_the_sky=True)

        return redirect("main:flights")

    if request.method == "POST" and "landed" in request.POST:
        flight = Flight.objects.get(id= request.POST.get("landed"))
        flight.landing = datetime.now(timezone.utc)
        flight.save()
        Person.objects.filter(id=flight.captain.id).update(in_the_sky=False)
        Person.objects.filter(id=flight.student.id).update(in_the_sky=False)
        Aircraft.objects.filter(id=flight.aircraft.id).update(in_the_sky=False)


    return render(request, "main/base.html", context)


def finished_flights(request):
    flights_list = Flight.objects.filter(landing__isnull = False, date = date.today()).order_by("-takeoff")

    context = {
        "flights_list": flights_list,
    }

    return render(request, "main/base_finished_flights.html", context)


def finished_flights_update(request, id):
    flight = Flight.objects.get(id=id)
    form = FlightForm(instance=flight)
    # flights_list = Flight.objects.order_by("id").exclude(landing__isnull=True)
    context = {
        "form": form,
        # "flights_list": flights_list,
    }

    if request.method == "POST":
        form = FlightForm(request.POST, instance=flight)
        if form.is_valid():
            form.save()
            return redirect("main:finished_flights")
    else:
        form = FlightForm(instance=flight)

    return render(request, "main/finished_flights_edit.html", context)


def end_day(request):

    flights_not_landed = Flight.objects.filter(landing__isnull = True)
    if request.method == "POST" and "ukoncit" in request.POST:
        #first we ckeck if all the flights are finished

        if flights_not_landed:
            print("You can't finish the day, there are still some aircrafts in the sky")
            messages.add_message(request, messages.WARNING, 'Nope. There are still some aircrafts in the sky.')

        else:
            #if all the flights are finished we deactivate people and aircrafts
            Person.objects.filter(active = True).update(active = False)
            Aircraft.objects.filter(active = True).update(active = False)
            return redirect("/main/")

    if request.method == "POST" and "stahnout" in request.POST:
        if flights_not_landed:
            messages.add_message(request, messages.WARNING, 'Nope. There are still some aircrafts in the sky.')
        else:
            todays_flights = Flight.objects.filter(date = date.today())
            response = HttpResponse(
                content_type='text/csv',
                headers={'Content-Disposition': f'attachment; filename="provoz_{date.today()}.csv"'},
            )
            writer = csv.writer(response, delimiter=',', dialect='excel')
            writer.writerow(["Datum", "Student", "Kapitan", "Letadlo", "Odlet", "Pristnani", "Delka"])
            for f in todays_flights:
                writer.writerow([f.date, f.student, f.captain, f.aircraft, f.takeoff, f.landing, f.duration ])
            return response
            #and we create a csv file based on the flights
    return render(request, "main/end_day.html")



#Additional funcsions

# def csv_end_day(flights):
#     with open ('first.csv', 'w', newline="") as csvfile:
#         writer = csv.writer(csvfile, delimiter=',', dialect='excel')
#         writer.writerow(["Datum", "Student", "Kapitan", "Letadlo", "Odlet", "Pristnani", "Delka"])
#         for f in flights:
#             writer.writerow([f.date, f.student, f.captain, f.aircraft, f.takeoff, f.landing, f.duration ])
#     return csvfile

casomira/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vuetify@3.1.5/dist/vuetify.min.css">
    <link rel="stylesheet" href="{% static 'main/flights.css' %}">
    {% block style %}{% endblock %}

    <title> {% block title %}Aktivni lety{% endblock %}</title>
</head>

<body>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    
    {%block main_content%}
    <div class="main-container" id="app_flights">
        <div>
            <div class="sticky">
                <div class="sidebar">
                    <img src="{% static 'main/logo.svg'%}" alt="Casomira" class="logo">
                    <a class="menu-btn" href='{% url "main:flights" %}'>Aktivní lety</a>
                    <a class="menu-btn" href='{% url "main:finished_flights" %}'>Ukončené lety</a>
                    <a class="menu-btn" href='{% url "main:end_day" %}'>Ukončit provoz</a>
                </div>
            </div>
        </div>


        <div class="main-window">
            <div class="header">
                <p>{% block name %}AKTIVNÍ LETY{% endblock %}</p>
            </div>
            {% block content %}
            <div class="content container">
                <div class="content-aktivni-lety">
                    <ul class="list-aktivni list-header">
                        <li class="let-aktivni let-header">
                            <p>Letadlo</p>
                            <p>Žák</p>
                            <p>Kapitán</p>
                            <p>Čas vzletů</p>
                            <a class='pristal-btn deactivate-btn' href="#"></a>
                        </li>
                            {% if flights_not_landed %}
                                {% for f in flights_not_landed %}
                                <form method="post">
                                    {% csrf_token %}
                                    <li class="let-aktivni">
                                        <p>{{f.aircraft}}</p>
                                        <p> {{f.student.last_name}}</p>
                                        <p> {{f.captain.last_name}}</p>
                                        <p> {{f.takeoff}}</p>
                                        <button type='submit' class='pristal-btn' name="landed" id="pristal-btn"
                                            value="{{f.id}}">PŘISTAL</button>
                                    </li>
                                </form>
                                {% endfor %}
                            {% else %}
                                <div class="no-flights">
                                    <p>Žádné lety k zobrazení</p>
                                </div>
                            {% endif %}

                    </ul>
                </div>
                <button @click="toggleNewFlight" class="pridat-btn" id="pridat-btn">Přidat let +</button>
            </div>
           


            <div v-show ="showNewFlight" class="pridat-novy-let " id="pridat-novy-let">
                <div class="header header-novy">
                    <p>NOVY LET</p>
                </div>
                <div class="content container">
                    <form method="post">
                        {% csrf_token %}
                        <div class="content content-novy">
                            <div class="content-novy-let">

                                <div class="choice">
                                    <select name="aircraft" id="aircraft">
                                        <option selected disabled hidden>Letadlo</option>
                                        {% for aircraft in aircraft_active_list %}
                                        <option value="{{aircraft.id}}" name="aircraft">{{aircraft.registration}}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="choice">
                                    <select name="student" id="student">
                                        <option selected disabled hidden>Zak</option>
                                        {% for person in person_active_list %}
                                        <option value="{{person.id}}" name="student">{{person.first_name}}
                                            {{person.last_name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                

                                <div class="choice">
                                    <select name="capitan" id="capitan">
                                        <option selected disabled hidden>Kapitan</option>
                                        {% for person in person_active_list %}
                                        <option value="{{person.id}}" name="capitan">{{person.first_name}}
                                            {{person.last_name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <a @click="toggleNewBowFlight" class='vlecna-btn' id="vlecna">+V</a>


                            </div>

                            <div v-show="showNewBowFlight" class="vlecna-let" id="vlecna-let">
                                <div class="choice">
                                    <select name="aircraft_bow" id="aircraft_bow">
                                        <option selected disabled hidden>Letadlo</option>
                                        {% for aircraft in aircraft_active_list %}
                                        <option value="{{aircraft.id}}" name="aircraft_bow">{{aircraft.registration}}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="choice">
                                    <select name="capitan_bow" id="capitan_bow">
                                        <option >Kapitan</option>
                                        {% for person in person_active_list %}
                                        <option value="{{person.id}}" name="capitan_bow">{{person.first_name}}
                                            {{person.last_name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <a class='vlecna-btn vlecna-smazat' id="vlecna-smazat">-</a>

                                <div class="choice hidden">
                                    <select name="no" id="no">
                                        <option selected disabled hidden>For syling</option>
                                    </select>
                                </div>

                            </div>
                            <button type='submit' class="pridat-btn potvrdit-btn" id="potvrdit-btn" name="confirm_takeoff"
                                value="confirm_takeoff">
                                Potvrdit vzlet
                            </button>
                        </div>
                    </form>
            </div>
        </div>

        {% endblock content %}

        {% endblock main_content %}

    </div>

    <script>
        const app = Vue.createApp({
            data(){
                return{
                    showNewFlight: false,
                    showNewBowFlight: false,
                    aircraftInTheSky: []
                }
            }, 
            methods: {
                toggleNewFlight(){
                    console.log("Hi")
                    this.showNewFlight = !this.showNewFlight;
                    console.log(this.aircraftInTheSky)
                },
                toggleNewBowFlight(){
                    this.showNewBowFlight = !this.showNewBowFlight;
                }
            }
        })
        const moundetApp = app.mount("#app_flights")
    </script>

    {% block script %}
    {% endblock script %}

</body>

</html>

casomira/main/templates/main/base_finished_flights.html
{% extends "./base.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/finished_flights.css' %}">{% endblock style %}

{% block name %}UKONČENÉ LETY{% endblock name %}

{% block content %}
<div class="content">
<ul class="list-aktivni list-header">
    <li class="let-aktivni let-header">
        <p>Letadlo</p>
        <p>Žák</p>
        <p>Kapitán</p>
        <p>Čas vzletů</p>
        <p>Čas přistání</p>
        <p>Delka létu</p>
        <button class="edit-flight disabled" disabled>Edit</button>
    </li>
    {% for f in flights_list %}
    <li class="let-aktivni" id="flight" value="{{f.id}}">
        <p>{{f.aircraft}}</p>
        <p> {{f.student.last_name}}</p>
        <p> {{f.captain.last_name}}</p>
        <p> {{f.takeoff.time}}</p>
        <p> {{f.landing.time}}</p>
        <p> {{f.duration}} min.</p>

        <a class="edit-flight" id="edit-flight" href="flights/{{f.id}}/edit">Edit</a>
    </li>

    {% endfor %}
</ul>
</div>


{% block update %}
{% endblock update %}



{% endblock content%}

{% block script %}
<script src="{% static 'main/finished_flights.js' %}"></script>
{% endblock script %}

casomira/main/templates/main/end_day.html
{% extends "./base.html" %}

{% load static %}

{% block main_content%}
<div class="are_you_sure">
    <div class="warning">
        <div class="header ukoncit-header">
            <p>UKONCIT PROVOZ</p>
        </div>
        <p>OPRAVDU CHCETE UKONCIT PROVOZ?</p>
        {% if messages %}
            {% for f in messages %}
                <div>  {{ f }} </div>
            {% endfor %}
        {% endif %}
        <div class="two_buttons">
            <form method="post">
                {% csrf_token %}
                <button type='submit' class='ukoncit_btn ukoncit_btn_ukoncit' name="ukoncit" id="ukoncit-btn">Ukoncit provoz</button>
                <button type='submit' class='ukoncit_btn ukoncit_btn_ukoncit' name="stahnout" id="ukoncit-btn">Stahnout prilohu</button>
            </form>
            <button type="button" onclick="javascript:history.back()" class="ukoncit_btn ukoncit_btn_vratit">Vratit se zpet</button>

        </div>
    </div>
</div>
{% endblock main_content%}

casomira/main/templates/main/entry.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/entry.css' %}">
</head>

<body >
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>

    <div class="navbar">
        <div class="casomira-logo">
            <img src="{% static 'main/logo.svg'%}" alt="Casomira" class="logo">
        </div>
    </div>

    <div class="main-window">
        <div class="header">
            <h1>ZAPIS DO PROVOZU</h1>
        </div>


        <form method="post" >
            {% csrf_token %}
            <div id="app">
            <div class="vyber-container" >
                <div class="person-container">                   
                    <div class="choice-header" id="choice-header" @click="toggleShowPeople">VÝBĚR OSOB</div>
                    <div class="dropdown-container">
                    <div v-show="showPeople" class="dropdown">
                        {% if person_list %}
                        {% for person in person_list %}
                        <div class="choice-container">
                            <input type="checkbox" value="{{person.id}}" name="person_choosen" id="person:{{person.id}}"
                                class="person" v-model="personChecked">
                            <label for='person'>{{person.first_name}} {{person.last_name}}</label>
                            <hr>
                        </div>
                        {% endfor %}
                        {% else %}
                        <h2>No people are available</h2>
                        {% endif %}
                        </div>
                    </div>
                </div>

                <div class="aircraft-container">
                    <div class="choice-header" id="choice-header" @click="toggleShowAircrafts">VÝBĚR LETADEL</div>
                    <div class="dropdown-container">
                        <div v-show="showAircrafts" class="dropdown">
                        {% if aircraft_list %}
                        {% for aircraft in aircraft_list %}
                        <div class="choice-container">

                            <input type="checkbox" value="{{aircraft.id}}" id="aircraft:{{aircraft.id}}"
                                name="aircraft_choosen" class="aircraft" :value="aircraft" v-model="aircraftChecked">
                            <label for="aircraft">{{aircraft.registration}}</label>
                            <hr>
                        </div>
                    {% endfor %}
                    {% else %}
                    <h2>No aircrafts are available</h2>
                    {% endif %}
                        </div>
                        </div>
                </div>


            </div>


            <div class="error-container" v-show="showError">
                <p class="error" id="error" >${ errorMessage }$</p>
            </div>

            <div class="btn-container">
                <button @click.stop="entryValidation"  type="submit" class="btn-zapis" id="zapis-btn" name="confirm_entry" value="confirm_entry">
                    Potvrdit zapis
                </button>
            </div>
            </div>
        </form>



    </div>
    <script>
        const app = Vue.createApp({

            data() {
            return {
              message: 'Hello Vue!',
              showPeople: false,
              showAircrafts: false,
              personChecked: [],
              aircraftChecked: [],
              showError: false,
              errorMessage: "Je nutné vybrat alespoň 1 letadlo a 2 osoby"
            }
          },
            methods:{
                toggleShowPeople(){
                    this.showPeople = !this.showPeople
                },
                toggleShowAircrafts(){
                    this.showAircrafts = !this.showAircrafts
                },
                entryValidation(event){
                    console.log(this.personChecked.length, this.aircraftChecked)
                     if (this.personChecked.length < 2 || this.aircraftChecked.length < 1){
                        this.showError = true;
                        event.preventDefault(); 
                     }else{
                        this.showError = false;
                     }
                }
            },
            compilerOptions: {
                delimiters: ["${", "}$"]
            },
        })
        const moundetApp = app.mount("#app")
      </script>

    <script src="{% static 'main/entry.js' %}"></script>
</body>

</html>

casomira/main/templates/main/finished_flights_edit.html
{% extends "./base_finished_flights.html" %}

{% load static %}

{% block update %}


<div class="edit-container">
  <div class="edit">
    <h1>Edit Flight</h1>

    <form class='edit-form' action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
  </div>
</div>


{% endblock update %}

casomira/main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/index.css' %}">
    <title>ZAHAJIT PROVOZ</title>
</head>

<body>
    <div class="main-window">
        <div class="casomira-logo">
            <img src="{% static 'main/logo.svg'%}" class="logo">
        </div>
        <a href='{% url "main:entry" %}' class="start">
            Zahajít provoz
        </a>
    </div>

</body>

</html>